feat: 🎸 add test code for matchings
dataswap/dataswapjs pull request #85
Opened 2023-12-28 15:03 UTC by siriusyim

✅ Closes: #6

## Related Issues

close

## Proposed Changes

## Additional Info

## Checklist

Before you mark the PR ready for review, please make sure that:

- [ ] Commits have a clear commit message.
- [ ] Tests exist for new functionality or change in behavior
- [ ] CI is green

2023-12-28 22:44 UTC, waynewyang requested changes

2023-12-28 22:44 UTC, waynewyang commented on test/assertions/module/matchingsAssertion.ts
> +        //TODO:https://github.com/dataswap/dataswapjs/issues/68
delete it ?
issue68 already ok

2023-12-28 22:44 UTC, waynewyang commented on test/helpers/module/matchingsHelper.ts
> +    getDatasetsHelper(): IDatasetsHelper {
add comment

2023-12-28 22:44 UTC, waynewyang commented on test/testkits/setup/generator.ts
> +
write the reason that why // the code,
or shoud delete the code?

2023-12-29 01:26 UTC, lovel8 approved these changes

2023-12-29 02:52 UTC, waynewyang approved these changes

2023-12-29 02:52 UTC, merged